# Generated by Django 5.0 on 2024-01-08 11:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_yeat', models.IntegerField()),
                ('number_in_stock', models.IntegerField()),
                ('daily_rate', models.FloatField()),
                ('date', models.CharField(default=datetime.datetime(2024, 1, 8, 16, 51, 34, 575028), max_length=100)),
                ('genre1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc', to='app.genre')),
            ],
        ),
    ]
